title: Andrii Nikolaiev, PhD
email: an682@cam.ac.uk
description: "Andrii's personal website."
baseurl: ""
url: "https://andynik.github.io"

facebook_username: andrn
github_username: andynik
linkedin_username: andynik

# Navigation (block style)
nav:
  - title: 'Research'
    href: '/research'
  - title: 'STEM Projects'
    href: '/stem-projects'
  - title: 'Interests'
    href: '/interests'
  - title: 'CV'
    href: '/cv/'   # local page that will redirect

theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - index.md
  - research.md
  - stem-projects.md
  - interests.md
  - cv.md
